import React, { useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { useApp } from '../../context/AppContext';
import { useLanguage } from '../../context/LanguageContext';
import { getStudentAvatar } from '../../services/avatarLibrary';
import { Badge } from '../../components/common/Badge';
import { Modal } from '../../components/common/Modal';
import {
  Briefcase,
  CheckSquare,
  ClipboardList,
  Award,
  Users,
  Bell,
  BarChart3,
  Search,
  Clock,
  AlertCircle,
  Plus,
  ArrowRight,
  FileSpreadsheet,
  CheckCircle2,
  Calendar,
  UserCheck
} from 'lucide-react';

interface TeacherWorkspacePageProps {
  setActiveTab: (tab: string) => void;
}

export const TeacherWorkspacePage: React.FC<TeacherWorkspacePageProps> = ({ setActiveTab }) => {
  const { currentUser, allProfiles } = useAuth();
  const { isKhmer, t } = useLanguage();
  const {
    classes,
    selectedClass,
    submissions,
    practicalExams,
    studentAnalytics,
    teacherReminders,
    toggleReminder,
    addTeacherReminder,
    learningActivities,
    directSubmissions
  } = useApp();

  const [studentSearch, setStudentSearch] = useState('');
  const [showAddReminderModal, setShowAddReminderModal] = useState(false);
  const [newReminderTitle, setNewReminderTitle] = useState('');
  const [newReminderDesc, setNewReminderDesc] = useState('');
  const [newReminderPriority, setNewReminderPriority] = useState<'low' | 'normal' | 'high' | 'urgent'>('normal');

  // Filter students by search
  const filteredStudents = allProfiles
    .filter(p => p.role === 'student')
    .filter(p => {
      const match = p.fullName.toLowerCase().includes(studentSearch.toLowerCase()) ||
                    (p.studentId && p.studentId.toLowerCase().includes(studentSearch.toLowerCase())) ||
                    (p.className && p.className.toLowerCase().includes(studentSearch.toLowerCase()));
      return match;
    });

  // Calculate task counts
  const pendingSubmissionsCount = submissions.filter(s => s.status === 'submitted').length + 
                                  directSubmissions.filter(d => d.status === 'pending').length;
  const attentionStudents = studentAnalytics.filter(s => s.needsAttention || s.attendancePercentage < 80);

  const handleAddReminder = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newReminderTitle.trim()) return;

    addTeacherReminder({
      title: newReminderTitle,
      description: newReminderDesc,
      isCompleted: false,
      priority: newReminderPriority,
      autoGenerated: false
    });

    setShowAddReminderModal(false);
    setNewReminderTitle('');
    setNewReminderDesc('');
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl sm:text-2xl font-black text-slate-900 flex items-center gap-2.5">
            <Briefcase className="w-6 h-6 text-zinc-900" />
            {t('title.workspace', undefined, 'Teacher Quick Workspace')}
          </h1>
          <p className="text-xs sm:text-sm text-slate-500 mt-0.5">
            {isKhmer
              ? 'មជ្ឈមណ្ឌលគ្រប់គ្រងការងារថ្នាក់រៀនប្រចាំថ្ងៃ សកម្មភាពរហ័ស និងការស្វែងរកសិស្ស។'
              : 'Command center for your daily classroom tasks, quick actions, and student lookups.'}
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => setActiveTab('attendance')}
            className="px-4 py-2.5 bg-zinc-900 hover:bg-zinc-800 text-white font-bold text-xs rounded-xl shadow-xs transition-all flex items-center gap-2 cursor-pointer"
          >
            <CheckSquare className="w-4 h-4 text-zinc-300" />
            <span>{isKhmer ? 'ស្រង់វត្តមានរហ័ស' : 'Fast Attendance'}</span>
          </button>
        </div>
      </div>

      {/* 8 Quick Actions Bar */}
      <div className="bg-white rounded-3xl p-5 sm:p-6 border border-zinc-200 shadow-xs space-y-3">
        <h2 className="text-xs font-black uppercase tracking-wider text-slate-400">
          {t('teacher.quick_actions', undefined, 'Quick Classroom Actions')}
        </h2>
        <div className="grid grid-cols-2 sm:grid-cols-4 md:grid-cols-8 gap-2.5">
          <button
            onClick={() => setActiveTab('attendance')}
            className="p-3 rounded-2xl bg-zinc-50 hover:bg-zinc-100 border border-zinc-200 text-slate-800 text-center transition-all flex flex-col items-center gap-1.5 group cursor-pointer"
          >
            <CheckSquare className="w-5 h-5 text-zinc-800 group-hover:scale-110 transition-transform" />
            <span className="text-[11px] font-bold">{isKhmer ? 'វត្តមាន' : 'Attendance'}</span>
          </button>

          <button
            onClick={() => setActiveTab('assignments')}
            className="p-3 rounded-2xl bg-zinc-50 hover:bg-zinc-100 border border-zinc-200 text-slate-800 text-center transition-all flex flex-col items-center gap-1.5 group cursor-pointer"
          >
            <ClipboardList className="w-5 h-5 text-zinc-800 group-hover:scale-110 transition-transform" />
            <span className="text-[11px] font-bold">{isKhmer ? 'កិច្ចការ' : 'Assignment'}</span>
          </button>

          <button
            onClick={() => setActiveTab('typing')}
            className="p-3 rounded-2xl bg-zinc-50 hover:bg-zinc-100 border border-zinc-200 text-slate-800 text-center transition-all flex flex-col items-center gap-1.5 group cursor-pointer"
          >
            <Award className="w-5 h-5 text-zinc-800 group-hover:scale-110 transition-transform" />
            <span className="text-[11px] font-bold">{isKhmer ? 'វាយអក្សរ' : 'Typing Lab'}</span>
          </button>

          <button
            onClick={() => setActiveTab('submissions')}
            className="p-3 rounded-2xl bg-zinc-50 hover:bg-zinc-100 border border-zinc-200 text-slate-800 text-center transition-all flex flex-col items-center gap-1.5 group cursor-pointer"
          >
            <FileSpreadsheet className="w-5 h-5 text-zinc-800 group-hover:scale-110 transition-transform" />
            <span className="text-[11px] font-bold">{isKhmer ? 'កិច្ចការផ្ញើ' : 'Upload Inbox'}</span>
          </button>

          <button
            onClick={() => setActiveTab('classes')}
            className="p-3 rounded-2xl bg-zinc-50 hover:bg-zinc-100 border border-zinc-200 text-slate-800 text-center transition-all flex flex-col items-center gap-1.5 group cursor-pointer"
          >
            <CheckCircle2 className="w-5 h-5 text-zinc-800 group-hover:scale-110 transition-transform" />
            <span className="text-[11px] font-bold">{isKhmer ? 'ថ្នាក់រៀន' : 'Classes'}</span>
          </button>

          <button
            onClick={() => setActiveTab('students')}
            className="p-3 rounded-2xl bg-zinc-50 hover:bg-zinc-100 border border-zinc-200 text-slate-800 text-center transition-all flex flex-col items-center gap-1.5 group cursor-pointer"
          >
            <Users className="w-5 h-5 text-zinc-800 group-hover:scale-110 transition-transform" />
            <span className="text-[11px] font-bold">{isKhmer ? 'បញ្ជីសិស្ស' : 'Students'}</span>
          </button>

          <button
            onClick={() => setShowAddReminderModal(true)}
            className="p-3 rounded-2xl bg-zinc-50 hover:bg-zinc-100 border border-zinc-200 text-slate-800 text-center transition-all flex flex-col items-center gap-1.5 group cursor-pointer"
          >
            <Plus className="w-5 h-5 text-zinc-800 group-hover:scale-110 transition-transform" />
            <span className="text-[11px] font-bold">{isKhmer ? 'កំណត់ត្រា' : 'Add Reminder'}</span>
          </button>

          <button
            onClick={() => setActiveTab('reports')}
            className="p-3 rounded-2xl bg-zinc-50 hover:bg-zinc-100 border border-zinc-200 text-slate-800 text-center transition-all flex flex-col items-center gap-1.5 group cursor-pointer"
          >
            <BarChart3 className="w-5 h-5 text-zinc-800 group-hover:scale-110 transition-transform" />
            <span className="text-[11px] font-bold">{isKhmer ? 'របាយការណ៍' : 'Reports'}</span>
          </button>
        </div>
      </div>

      {/* Main Grid: Today's Tasks & Instant Student Search */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Today's Work & Tasks (7 Cols) */}
        <div className="lg:col-span-7 space-y-6">
          {/* Today's Work Summary Cards */}
          <div className="bg-white rounded-3xl p-6 border border-zinc-200 shadow-xs space-y-4">
            <div className="flex items-center justify-between">
              <h2 className="text-sm font-black uppercase tracking-wide text-slate-800 flex items-center gap-2">
                <Clock className="w-4 h-4 text-zinc-800" />
                Today's Work & Priorities
              </h2>
              <span className="text-xs font-mono text-slate-400">August 21, 2026</span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {/* Attendance Card */}
              <div
                onClick={() => setActiveTab('attendance')}
                className="p-4 rounded-2xl border border-zinc-200 bg-zinc-50 hover:border-zinc-300 transition-all cursor-pointer space-y-1.5"
              >
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-zinc-900">Attendance</span>
                  <Badge variant="green" size="sm">Completed</Badge>
                </div>
                <p className="text-sm font-extrabold text-slate-900">Grade 10A (32 Present)</p>
                <p className="text-[11px] text-slate-500">2 absent, 1 late recorded today</p>
              </div>

              {/* Pending Grading Card */}
              <div
                onClick={() => setActiveTab('assignments')}
                className="p-4 rounded-2xl border border-zinc-200 bg-zinc-50 hover:border-zinc-300 transition-all cursor-pointer space-y-1.5"
              >
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-zinc-900">Waiting for Grading</span>
                  <Badge variant="black" size="sm">{pendingSubmissionsCount} Pending</Badge>
                </div>
                <p className="text-sm font-extrabold text-slate-900">Student Work & Notes</p>
                <p className="text-[11px] text-slate-500">Includes Excel exercises & direct notes</p>
              </div>

              {/* Upcoming Exam Card */}
              <div
                onClick={() => setActiveTab('practicals')}
                className="p-4 rounded-2xl border border-zinc-200 bg-zinc-50 hover:border-zinc-300 transition-all cursor-pointer space-y-1.5"
              >
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-zinc-900">Upcoming Practical Exam</span>
                  <Badge variant="purple" size="sm">Aug 27</Badge>
                </div>
                <p className="text-sm font-extrabold text-slate-900">Microsoft Word Practical</p>
                <p className="text-[11px] text-slate-500">6 tasks • Duration: 60 minutes</p>
              </div>

              {/* Attention Alert Card */}
              <div
                onClick={() => setActiveTab('students')}
                className="p-4 rounded-2xl border border-zinc-200 bg-zinc-50 hover:border-zinc-300 transition-all cursor-pointer space-y-1.5"
              >
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-zinc-900">Students Needing Help</span>
                  <Badge variant="red" size="sm">{attentionStudents.length} Students</Badge>
                </div>
                <p className="text-sm font-extrabold text-slate-900">Attendance & Score Warning</p>
                <p className="text-[11px] text-slate-500">SOK Sopheak, LONG Rath</p>
              </div>
            </div>
          </div>

          {/* Teacher Checklist & Reminders */}
          <div className="bg-white rounded-3xl p-6 border border-zinc-200 shadow-xs space-y-4">
            <div className="flex items-center justify-between">
              <h2 className="text-sm font-black uppercase tracking-wide text-slate-800 flex items-center gap-2">
                <CheckSquare className="w-4 h-4 text-zinc-800" />
                Teacher Reminders & To-Do
              </h2>
              <button
                onClick={() => setShowAddReminderModal(true)}
                className="text-xs font-bold text-zinc-900 hover:underline flex items-center gap-1 cursor-pointer"
              >
                <Plus className="w-3.5 h-3.5" />
                <span>Add Task</span>
              </button>
            </div>

            <div className="space-y-2">
              {teacherReminders.map((rem) => (
                <div
                  key={rem.id}
                  onClick={() => toggleReminder(rem.id)}
                  className={`p-3.5 rounded-2xl border transition-all flex items-start gap-3 cursor-pointer ${
                    rem.isCompleted
                      ? 'bg-zinc-50 border-zinc-200 opacity-60'
                      : 'bg-white border-zinc-200 hover:border-zinc-300'
                  }`}
                >
                  <input
                    type="checkbox"
                    checked={rem.isCompleted}
                    onChange={() => {}}
                    className="accent-zinc-900 rounded mt-0.5 cursor-pointer"
                  />
                  <div className="flex-1 min-w-0">
                    <p className={`text-xs font-bold ${rem.isCompleted ? 'line-through text-slate-500' : 'text-slate-900'}`}>
                      {rem.title}
                    </p>
                    <p className="text-[11px] text-slate-500 mt-0.5">{rem.description}</p>
                  </div>
                  {rem.priority === 'urgent' && (
                    <Badge variant="red" size="sm">Urgent</Badge>
                  )}
                  {rem.priority === 'high' && (
                    <Badge variant="amber" size="sm">High</Badge>
                  )}
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Right Column: Quick Student Search & Recent Activity (5 Cols) */}
        <div className="lg:col-span-5 space-y-6">
          {/* Quick Student Search */}
          <div className="bg-white rounded-3xl p-6 border border-zinc-200 shadow-xs space-y-4">
            <h2 className="text-sm font-black uppercase tracking-wide text-slate-800 flex items-center gap-2">
              <Users className="w-4 h-4 text-zinc-800" />
              Quick Student Directory Search
            </h2>

            <div className="relative">
              <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
              <input
                type="text"
                value={studentSearch}
                onChange={(e) => setStudentSearch(e.target.value)}
                placeholder="Search by student name, ID (e.g. STD-2026-001) or class..."
                className="w-full pl-9 pr-3.5 py-2.5 text-xs bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-zinc-400/20 focus:border-zinc-800 outline-none transition-all"
              />
            </div>

            <div className="divide-y divide-slate-100 max-h-64 overflow-y-auto pr-1">
              {filteredStudents.slice(0, 5).map((student) => (
                <div
                  key={student.id}
                  onClick={() => setActiveTab('students')}
                  className="py-2.5 flex items-center justify-between hover:bg-slate-50 px-2 rounded-xl cursor-pointer transition-colors"
                >
                  <div className="flex items-center gap-2.5 min-w-0">
                    <img
                      src={student.avatarUrl || getStudentAvatar(student.studentId || student.fullName)}
                      alt={student.fullName}
                      className="w-8 h-8 rounded-lg object-cover ring-1 ring-slate-200 shrink-0"
                    />
                    <div className="min-w-0">
                      <p className="text-xs font-bold text-slate-900 truncate">{student.fullName}</p>
                      <p className="text-[10px] text-slate-400 font-mono">{student.studentId} • {student.className}</p>
                    </div>
                  </div>
                  <ArrowRight className="w-3.5 h-3.5 text-slate-400 shrink-0" />
                </div>
              ))}
            </div>
          </div>

          {/* Recent Classroom Activity Feed */}
          <div className="bg-white rounded-3xl p-6 border border-slate-200 shadow-sm space-y-4">
            <h2 className="text-sm font-black uppercase tracking-wide text-slate-800 flex items-center gap-2">
              <Clock className="w-4 h-4 text-pink-700" />
              Live Classroom Activity
            </h2>

            <div className="divide-y divide-slate-100">
              {learningActivities.slice(0, 5).map((act) => (
                <div key={act.id} className="py-2.5 flex items-start gap-2.5 text-xs">
                  <span className="w-2 h-2 rounded-full bg-pink-700 mt-1.5 shrink-0"></span>
                  <div className="min-w-0 flex-1">
                    <p className="font-bold text-slate-900">{act.title}</p>
                    <p className="text-[11px] text-slate-500 mt-0.5">{act.description}</p>
                    <span className="text-[10px] text-slate-400 font-mono mt-1 block">{act.timestamp}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Add Reminder Modal */}
      {showAddReminderModal && (
        <Modal
          isOpen={showAddReminderModal}
          onClose={() => setShowAddReminderModal(false)}
          title="Add Quick Teacher Reminder"
          subtitle="Schedule a reminder for yourself in the teacher workspace"
        >
          <form onSubmit={handleAddReminder} className="space-y-4">
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Reminder Title
              </label>
              <input
                type="text"
                required
                value={newReminderTitle}
                onChange={(e) => setNewReminderTitle(e.target.value)}
                placeholder="e.g. Prepare Excel lab exercise templates for Grade 10B"
                className="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-pink-500/20 focus:border-pink-600 outline-none font-semibold"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Details / Notes
              </label>
              <textarea
                rows={3}
                value={newReminderDesc}
                onChange={(e) => setNewReminderDesc(e.target.value)}
                placeholder="Additional notes for your reminder..."
                className="w-full p-3 text-xs bg-slate-50 border border-slate-200 rounded-xl outline-none"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Priority Level
              </label>
              <select
                value={newReminderPriority}
                onChange={(e) => setNewReminderPriority(e.target.value as any)}
                className="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl outline-none font-semibold"
              >
                <option value="normal">Normal</option>
                <option value="high">High</option>
                <option value="urgent">Urgent</option>
                <option value="low">Low</option>
              </select>
            </div>

            <div className="pt-4 border-t border-slate-100 flex items-center justify-end gap-2">
              <button
                type="button"
                onClick={() => setShowAddReminderModal(false)}
                className="px-4 py-2 text-xs font-semibold text-slate-500 hover:text-slate-800"
              >
                Cancel
              </button>
              <button
                type="submit"
                className="px-5 py-2.5 bg-pink-700 hover:bg-pink-800 text-white font-bold text-xs rounded-xl shadow-sm transition-colors"
              >
                Save Reminder
              </button>
            </div>
          </form>
        </Modal>
      )}
    </div>
  );
};
